/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package struktur.dasar;

import java.util.Date;

import org.apache.commons.lang3.time.DateUtils;

import struktur.dasar.kendaraan.Kereta;
import struktur.dasar.kendaraan.Mobil;
import struktur.dasar.kendaraan.Motor;
import struktur.dasar.music.Gitar;

public class App {
    public static void main(String[] args) {

        Gitar.bunyi();
		
		Mobil.jumlahBan();
		Motor.jumlahBan();
        Kereta.jumlahBan();
        
        Date today = new Date();
		System.out.println("hari ini : "+ today);
		Date tomorrow = DateUtils.addDays(today, 1);
		System.out.println("besok = "+ tomorrow);

    }
}
