/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package input.output;

import java.io.BufferedReader;
import java.io.InputStreamReader;
public class App {

    public static void main(String[] args) {


        // penggunaan Scanner

        // Scanner scanner = new Scanner(System.in);
        // System.out.println("Program penjumlahan sederhana");
        // System.out.print("Masukan angka pertama : \n");
        // int value1 = scanner.nextInt();
        // System.err.print("Masukan angka kedua : \n");
        // int value2 = scanner.nextInt();
        // int hasil = value1 + value2;
        // System.out.println("hasil : " + hasil);

        // penggunaan BufferedReader

        InputStreamReader streamReader = new InputStreamReader(System.in);
        BufferedReader bufferedReader = new BufferedReader(streamReader);
        System.out.println("Program penjumlahan sederhana");
        int value3 = 0;
        int value4 = 0;
        try {
            System.out.print("Masukan angka pertama : \n");
            value3 = Integer.parseInt(bufferedReader.readLine());
            System.out.print("Masukan angka kedua : \n");
            value4 = Integer.parseInt(bufferedReader.readLine());
        } catch (Exception e) {
            e.printStackTrace();
        }

        int hasil = value3 + value4;
        System.out.println("hasil : " + hasil);
    }
}
